# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e614bdee86ccc927ee367580cc874e8e3f5b7568be04d0b0f6e38911f8b90cf22496fcf57a401e6e02acf1547aded39ddae046aa30fe8df8112ef937bc0c86ff

test:
  secret_key_base: ddd8b72114cf87225a67372e58a04deb4de3b65adcd4fa63413267bf2093e97d33f72acf29e2b87969bf8e5faceb9a87a9743e1e6ac9e99faa331d2120b50693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
